version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chatbot_api
    restart: unless-stopped
    depends_on:
      - memcached
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - app-logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  memcached:
    image: memcached:1.6-alpine
    container_name: chatbot_memcache
    restart: unless-stopped

volumes:
  app-logs:
    driver: local