services:
  web:
    build: .
    container_name: chatbot_api_prod
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
    command: gunicorn --workers 3 --bind 0.0.0.0:5000 "app:create_app()"
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    container_name: chatbot_redis_prod
    expose:
      - "6379"


volumes: {}