# docker-compose.yml
version: '3.8'

services:
  web:
    build: .
    container_name: Syllabus_QA_Chatbot
    ports:
      - "5000:5000"
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - .:/app
      - logs:/app/logs
    depends_on:
      - memcached
      - redis

  
  worker:
    build: .
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - logs:/app/logs
    command: ["celery", "-A", "app.celery_worker.celery", "worker", "--loglevel=info"]
    depends_on:
      - redis 

  
  redis:
    image: "redis:7-alpine"
    restart: unless-stopped
    volumes:
      - redis_data:/data

  memcached:
    image: memcached:1.6-alpine
    restart: unless-stopped

volumes:
  logs:
    driver: local
  redis_data:
    driver: local