# docker-compose.yml
version: '3.8'

services:
  web:
    build: .
    container_name: Syllabus_QA_Chatbot
    ports:
      - "5000:5000"
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - logs:/app/logs 

    depends_on:
      - memcached

  memcached:
    image: memcached:1.6-alpine
    restart: unless-stopped
volumes:
  logs:
    driver: local 
