
services:
  web:
    build: .
    container_name: pdf_chat_app
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    env_file:
      - .env
    command: gunicorn --workers 2 --bind 0.0.0.0:5000 "app:create_app()"