"""Add processing_error to Document

Revision ID: 0d6cc9757d4e
Revises: 9abaf5c3e3c5
Create Date: 2025-08-12 11:52:11.436466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d6cc9757d4e'
down_revision = '9abaf5c3e3c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('processing_error', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_column('processing_error')

    # ### end Alembic commands ###
